// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tracing.proto

package tipb

import (
	"fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	github_com_golang_protobuf_proto "github.com/golang/protobuf/proto"

	io "io"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TracingEvent int32

const (
	TracingEvent_Unknown            TracingEvent = 0
	TracingEvent_TiKvGrpcio         TracingEvent = 500
	TracingEvent_TiKvSnapshot       TracingEvent = 501
	TracingEvent_TiKvTlsEngine      TracingEvent = 502
	TracingEvent_TiKvCollectMetrics TracingEvent = 503
	// Coprocessor
	TracingEvent_TiKvCoprocessor      TracingEvent = 1000
	TracingEvent_TiKvCoprScheduleTask TracingEvent = 1001
	// RawGet
	TracingEvent_TiKvRawGet         TracingEvent = 1100
	TracingEvent_TiKvRawGetTask     TracingEvent = 1101
	TracingEvent_TiKvRawGetKeyValue TracingEvent = 1102
	// Async_write
	TracingEvent_TiKvScheduleWriteTask                TracingEvent = 1200
	TracingEvent_TiKvEngineRunner                     TracingEvent = 1201
	TracingEvent_TiKvRawDelete                        TracingEvent = 1202
	TracingEvent_TiKvEngineDelete                     TracingEvent = 1203
	TracingEvent_TiKvRawPut                           TracingEvent = 1204
	TracingEvent_TiKvEnginePut                        TracingEvent = 1205
	TracingEvent_TiKvRawDeleteRange                   TracingEvent = 1206
	TracingEvent_TiKvEngineDeleteRange                TracingEvent = 1207
	TracingEvent_TiKvRaftKvAsyncWrite                 TracingEvent = 1208
	TracingEvent_TiKvRaftKvExecWriteRequests          TracingEvent = 1209
	TracingEvent_TiKvRaftKvExecWriteRequestsCallback  TracingEvent = 1216
	TracingEvent_TiKvRaftStoreOnWriteResult           TracingEvent = 1210
	TracingEvent_TiKvRaftStoreFsmPeerHandleMsg        TracingEvent = 1211
	TracingEvent_TiKvRaftStoreSendCommandTxnExtra     TracingEvent = 1212
	TracingEvent_TiKvRaftStoreRaftCommand             TracingEvent = 1213
	TracingEvent_TiKvRaftStoreProposeBatchRaftCommand TracingEvent = 1214
	TracingEvent_TiKvRaftStoreProposeRaftCommand      TracingEvent = 1215
)

var TracingEvent_name = map[int32]string{
	0:    "Unknown",
	500:  "TiKvGrpcio",
	501:  "TiKvSnapshot",
	502:  "TiKvTlsEngine",
	503:  "TiKvCollectMetrics",
	1000: "TiKvCoprocessor",
	1001: "TiKvCoprScheduleTask",
	1100: "TiKvRawGet",
	1101: "TiKvRawGetTask",
	1102: "TiKvRawGetKeyValue",
	1200: "TiKvScheduleWriteTask",
	1201: "TiKvEngineRunner",
	1202: "TiKvRawDelete",
	1203: "TiKvEngineDelete",
	1204: "TiKvRawPut",
	1205: "TiKvEnginePut",
	1206: "TiKvRawDeleteRange",
	1207: "TiKvEngineDeleteRange",
	1208: "TiKvRaftKvAsyncWrite",
	1209: "TiKvRaftKvExecWriteRequests",
	1216: "TiKvRaftKvExecWriteRequestsCallback",
	1210: "TiKvRaftStoreOnWriteResult",
	1211: "TiKvRaftStoreFsmPeerHandleMsg",
	1212: "TiKvRaftStoreSendCommandTxnExtra",
	1213: "TiKvRaftStoreRaftCommand",
	1214: "TiKvRaftStoreProposeBatchRaftCommand",
	1215: "TiKvRaftStoreProposeRaftCommand",
}
var TracingEvent_value = map[string]int32{
	"Unknown":                              0,
	"TiKvGrpcio":                           500,
	"TiKvSnapshot":                         501,
	"TiKvTlsEngine":                        502,
	"TiKvCollectMetrics":                   503,
	"TiKvCoprocessor":                      1000,
	"TiKvCoprScheduleTask":                 1001,
	"TiKvRawGet":                           1100,
	"TiKvRawGetTask":                       1101,
	"TiKvRawGetKeyValue":                   1102,
	"TiKvScheduleWriteTask":                1200,
	"TiKvEngineRunner":                     1201,
	"TiKvRawDelete":                        1202,
	"TiKvEngineDelete":                     1203,
	"TiKvRawPut":                           1204,
	"TiKvEnginePut":                        1205,
	"TiKvRawDeleteRange":                   1206,
	"TiKvEngineDeleteRange":                1207,
	"TiKvRaftKvAsyncWrite":                 1208,
	"TiKvRaftKvExecWriteRequests":          1209,
	"TiKvRaftKvExecWriteRequestsCallback":  1216,
	"TiKvRaftStoreOnWriteResult":           1210,
	"TiKvRaftStoreFsmPeerHandleMsg":        1211,
	"TiKvRaftStoreSendCommandTxnExtra":     1212,
	"TiKvRaftStoreRaftCommand":             1213,
	"TiKvRaftStoreProposeBatchRaftCommand": 1214,
	"TiKvRaftStoreProposeRaftCommand":      1215,
}

func (x TracingEvent) Enum() *TracingEvent {
	p := new(TracingEvent)
	*p = x
	return p
}
func (x TracingEvent) String() string {
	return proto.EnumName(TracingEvent_name, int32(x))
}
func (x *TracingEvent) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TracingEvent_value, data, "TracingEvent")
	if err != nil {
		return err
	}
	*x = TracingEvent(value)
	return nil
}
func (TracingEvent) EnumDescriptor() ([]byte, []int) { return fileDescriptorTracing, []int{0} }

type TracingProperty_Key int32

const (
	TracingProperty_Unknown TracingProperty_Key = 0
	TracingProperty_Foo     TracingProperty_Key = 1000
)

var TracingProperty_Key_name = map[int32]string{
	0:    "Unknown",
	1000: "Foo",
}
var TracingProperty_Key_value = map[string]int32{
	"Unknown": 0,
	"Foo":     1000,
}

func (x TracingProperty_Key) Enum() *TracingProperty_Key {
	p := new(TracingProperty_Key)
	*p = x
	return p
}
func (x TracingProperty_Key) String() string {
	return proto.EnumName(TracingProperty_Key_name, int32(x))
}
func (x *TracingProperty_Key) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TracingProperty_Key_value, data, "TracingProperty_Key")
	if err != nil {
		return err
	}
	*x = TracingProperty_Key(value)
	return nil
}
func (TracingProperty_Key) EnumDescriptor() ([]byte, []int) { return fileDescriptorTracing, []int{0, 0} }

type TracingProperty struct {
	Key              *TracingProperty_Key `protobuf:"varint,1,req,name=key,enum=tipb.TracingProperty_Key" json:"key,omitempty"`
	Value            *string              `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *TracingProperty) Reset()                    { *m = TracingProperty{} }
func (m *TracingProperty) String() string            { return proto.CompactTextString(m) }
func (*TracingProperty) ProtoMessage()               {}
func (*TracingProperty) Descriptor() ([]byte, []int) { return fileDescriptorTracing, []int{0} }

func (m *TracingProperty) GetKey() TracingProperty_Key {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return TracingProperty_Unknown
}

func (m *TracingProperty) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*TracingProperty)(nil), "tipb.TracingProperty")
	proto.RegisterEnum("tipb.TracingEvent", TracingEvent_name, TracingEvent_value)
	proto.RegisterEnum("tipb.TracingProperty_Key", TracingProperty_Key_name, TracingProperty_Key_value)
}
func (m *TracingProperty) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TracingProperty) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Key == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTracing(dAtA, i, uint64(*m.Key))
	}
	if m.Value == nil {
		return 0, new(github_com_golang_protobuf_proto.RequiredNotSetError)
	} else {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTracing(dAtA, i, uint64(len(*m.Value)))
		i += copy(dAtA[i:], *m.Value)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintTracing(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *TracingProperty) Size() (n int) {
	var l int
	_ = l
	if m.Key != nil {
		n += 1 + sovTracing(uint64(*m.Key))
	}
	if m.Value != nil {
		l = len(*m.Value)
		n += 1 + l + sovTracing(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovTracing(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTracing(x uint64) (n int) {
	return sovTracing(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TracingProperty) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTracing
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TracingProperty: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TracingProperty: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var v TracingProperty_Key
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (TracingProperty_Key(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Key = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTracing
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Value = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		default:
			iNdEx = preIndex
			skippy, err := skipTracing(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTracing
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return new(github_com_golang_protobuf_proto.RequiredNotSetError)
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTracing(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTracing
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTracing
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTracing
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthTracing
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTracing
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTracing(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTracing = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTracing   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("tracing.proto", fileDescriptorTracing) }

var fileDescriptorTracing = []byte{
	// 570 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x4b, 0x6f, 0xd3, 0x4c,
	0x14, 0x86, 0x9b, 0xfa, 0xab, 0x92, 0x39, 0x5f, 0x2f, 0xc3, 0x90, 0x8a, 0xb6, 0xd0, 0x34, 0x2a,
	0x45, 0x6a, 0x41, 0x32, 0x12, 0xff, 0x80, 0x96, 0xb4, 0x48, 0x51, 0x45, 0xe4, 0x04, 0x58, 0x4f,
	0x9d, 0x83, 0x63, 0xc5, 0x99, 0x31, 0x33, 0xe3, 0x24, 0xfe, 0x27, 0xfc, 0x0c, 0xee, 0xf7, 0xdb,
	0x92, 0x05, 0x20, 0x76, 0x6c, 0x51, 0xd8, 0x94, 0x3d, 0x97, 0x2d, 0x72, 0x1c, 0xd3, 0xa4, 0x42,
	0xec, 0x26, 0xcf, 0xfb, 0x9c, 0x93, 0x77, 0x2c, 0x1b, 0xe6, 0x8c, 0xe2, 0xae, 0x2f, 0x3c, 0x3b,
	0x54, 0xd2, 0x48, 0xf6, 0x9f, 0xf1, 0xc3, 0x83, 0x95, 0xa2, 0x27, 0x3d, 0x39, 0x04, 0x17, 0x93,
	0x53, 0x9a, 0xad, 0x2b, 0x58, 0x68, 0xa4, 0x72, 0x4d, 0xc9, 0x10, 0x95, 0x89, 0xd9, 0x05, 0xb0,
	0xda, 0x18, 0x2f, 0xe5, 0xca, 0xd3, 0x9b, 0xf3, 0x97, 0x96, 0xed, 0x64, 0xd8, 0x3e, 0xe6, 0xd8,
	0x55, 0x8c, 0x9d, 0xc4, 0x62, 0x45, 0x98, 0xe9, 0xf2, 0x20, 0xc2, 0xa5, 0xe9, 0xf2, 0xf4, 0x26,
	0x71, 0xd2, 0x1f, 0xeb, 0x67, 0xc0, 0xaa, 0x62, 0xcc, 0xfe, 0x87, 0xfc, 0x75, 0xd1, 0x16, 0xb2,
	0x27, 0xe8, 0x14, 0x2b, 0x80, 0xb5, 0x2b, 0x25, 0x3d, 0xcc, 0x9f, 0xff, 0x3c, 0x03, 0xb3, 0xa3,
	0x85, 0x95, 0x2e, 0x0a, 0x33, 0xe9, 0x2d, 0x00, 0x34, 0xfc, 0x6a, 0x77, 0x4f, 0x85, 0xae, 0x2f,
	0xe9, 0x77, 0x8b, 0x9d, 0x80, 0xd9, 0x04, 0xd4, 0x05, 0x0f, 0x75, 0x4b, 0x1a, 0xfa, 0xc3, 0x62,
	0x0c, 0xe6, 0x12, 0xd4, 0x08, 0x74, 0x45, 0x78, 0xbe, 0x40, 0xfa, 0xd3, 0x62, 0xa7, 0x80, 0x25,
	0x6c, 0x47, 0x06, 0x01, 0xba, 0x66, 0x1f, 0x8d, 0xf2, 0x5d, 0x4d, 0x7f, 0x59, 0xac, 0x08, 0x0b,
	0x69, 0x10, 0x2a, 0xe9, 0xa2, 0xd6, 0x52, 0xd1, 0xc3, 0x3c, 0x5b, 0x86, 0x62, 0x46, 0xeb, 0x6e,
	0x0b, 0x9b, 0x51, 0x80, 0x0d, 0xae, 0xdb, 0xf4, 0x5b, 0x3e, 0x6b, 0xe0, 0xf0, 0xde, 0x1e, 0x1a,
	0xfa, 0xbe, 0xc0, 0x4e, 0xc2, 0xfc, 0x11, 0x18, 0x5a, 0x1f, 0x0a, 0xd9, 0xff, 0xa5, 0xb0, 0x8a,
	0xf1, 0x8d, 0xe4, 0xe6, 0xf4, 0x63, 0x81, 0xad, 0xc0, 0xe2, 0xb0, 0xef, 0x68, 0xeb, 0x4d, 0xe5,
	0x9b, 0x74, 0xf5, 0x5d, 0xc2, 0x16, 0x81, 0x26, 0x59, 0xda, 0xda, 0x89, 0x84, 0x40, 0x45, 0xef,
	0x91, 0xec, 0x3e, 0x0e, 0xef, 0x5d, 0xc1, 0x00, 0x0d, 0xd2, 0xfb, 0xc7, 0xd4, 0x11, 0x7e, 0x40,
	0xc6, 0xca, 0xd5, 0x22, 0x43, 0x1f, 0xfe, 0x99, 0x4d, 0xbd, 0x84, 0x3d, 0x22, 0x63, 0xdd, 0xd2,
	0x41, 0x87, 0x0b, 0x0f, 0xe9, 0x63, 0x92, 0x75, 0x1b, 0x5f, 0x9a, 0x66, 0x4f, 0x48, 0xf6, 0x44,
	0x1c, 0x7e, 0xcb, 0x54, 0xbb, 0x97, 0x75, 0x2c, 0xdc, 0x61, 0x75, 0xfa, 0x94, 0xb0, 0x32, 0x9c,
	0x3e, 0x8a, 0x2a, 0x7d, 0x4c, 0x13, 0x07, 0x6f, 0x47, 0xa8, 0x8d, 0xa6, 0xcf, 0x08, 0xdb, 0x84,
	0xb3, 0xff, 0x30, 0x76, 0x78, 0x10, 0x1c, 0x70, 0xb7, 0x4d, 0xdf, 0x12, 0xb6, 0x06, 0x2b, 0x99,
	0x59, 0x37, 0x52, 0xe1, 0x35, 0x31, 0x52, 0x75, 0x14, 0x18, 0xfa, 0x9c, 0xb0, 0x75, 0x58, 0x9d,
	0x10, 0x76, 0x75, 0xa7, 0x86, 0xa8, 0xae, 0x72, 0xd1, 0x0c, 0x70, 0x5f, 0x7b, 0xf4, 0x05, 0x61,
	0xe7, 0xa0, 0x3c, 0xe1, 0xd4, 0x51, 0x34, 0x77, 0x64, 0xa7, 0xc3, 0x45, 0xb3, 0xd1, 0x17, 0x95,
	0xbe, 0x51, 0x9c, 0xbe, 0x24, 0x6c, 0x15, 0x96, 0x26, 0xb4, 0xe4, 0x30, 0xd2, 0xe8, 0x2b, 0xc2,
	0xb6, 0x60, 0x63, 0x22, 0x4e, 0x5e, 0x6f, 0xa9, 0x71, 0x9b, 0x1b, 0xb7, 0x35, 0xae, 0xbe, 0x26,
	0x6c, 0x03, 0xd6, 0xfe, 0xa6, 0x8e, 0x5b, 0x6f, 0xc8, 0xf6, 0xd6, 0xbb, 0x41, 0x29, 0xf7, 0x69,
	0x50, 0xca, 0x7d, 0x19, 0x94, 0x72, 0x77, 0xbe, 0x96, 0xa6, 0x60, 0xd1, 0x95, 0x1d, 0x3b, 0xf4,
	0x85, 0xe7, 0xf2, 0xd0, 0x36, 0x7e, 0xf3, 0x60, 0xf8, 0x3d, 0xd5, 0x72, 0xbf, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x04, 0xf4, 0x05, 0xdd, 0xa4, 0x03, 0x00, 0x00,
}
